"""The turn driver: run the loop forward until it needs the learner, then stop.

The Router already decides *what* comes next and hands back a :class:`RouteDecision`.
Nothing consumed it: each ``SessionRunner.run_*`` call is a single step, so a caller had
to re-implement the state machine to know that (say) a ``wakeup.distill`` must be followed
by a ``finish_*``. That knowledge must live server-side. ``TurnDriver.advance`` closes the
loop: given a decision, it runs every *non-learner* step (teach, distill, finish, point-next)
in order and stops the instant it reaches a probe/test that needs a human answer.

Contract — the driver adds no learning intelligence:

- **No judgment.** It chooses no verdict, no category, no route, no axis. It only dispatches
  on ``decision.next_step``; every branch delegates to an existing ``SessionRunner`` call, and
  the *next* decision always comes back from the Router, never from the driver.
- **Cannot spin.** The Router already terminates, but a defensive hop ceiling guarantees the
  driver returns even if a future engine change ever produced a cycle.
- **Owns turn ids.** The driver mints the ``turn_id`` when it presents a question and returns
  it; the caller echoes that id back on the matching answer so probe and grade pair up.
"""
from __future__ import annotations

from dataclasses import dataclass

from .errors import InvariantError
from .routing import RouteDecision
from .session import SessionRunner

# Defensive: the Router terminates on its own; this only bounds a hypothetical cycle so a
# single ``advance`` can never hang. One learner-facing unit needs far fewer hops than this.
_MAX_HOPS = 256


@dataclass(frozen=True, slots=True)
class DriverState:
    """What one ``advance`` produced for the transport/UI layer.

    ``status`` is one of ``awaiting_learner`` (a question is posed and the loop is paused for
    an answer), ``parked`` (the journey was distilled + parked and needs an explicit resume),
    or ``done`` (the ladder has no next unit). Only ``awaiting_learner`` carries a live
    ``turn_id`` the caller must echo back on the answer.
    """

    status: str
    journey_id: int
    projection_revision: int
    turn_id: str | None = None
    unit_id: int | None = None
    axis: str | None = None
    question: str | None = None
    step: str | None = None
    highlight: bool = False
    resume_question: str | None = None
    reason: str = ""


class TurnDriver:
    """Drive the deterministic loop over :class:`SessionRunner` until a learner is needed."""

    def __init__(self, session: SessionRunner) -> None:
        self.session = session
        self._turn_seq = 0

    def advance(self, *, journey_id: int, decision: RouteDecision | None) -> DriverState:
        """Run non-learner steps until a probe/test, a park, or ladder completion."""
        for _ in range(_MAX_HOPS):
            if decision is None or decision.next_step is None:
                return self._done(journey_id, decision)

            step = decision.next_step
            if step in {"wakeup.probe", "wakeup.test"}:
                return self._await_learner(journey_id, decision, step)
            if step == "wakeup.teach":
                decision = self._teach_then_probe(journey_id, decision)
                continue
            if step == "wakeup.distill":
                decision = self._distill_then_finish(journey_id, decision)
                if decision is None:  # unit was parked, not finished
                    return self._parked(journey_id, decision)
                continue
            raise InvariantError(f"driver cannot dispatch next_step {step!r}")

        raise InvariantError("driver exceeded its hop ceiling without reaching the learner")

    # -- step handlers ------------------------------------------------------------

    def _await_learner(self, journey_id: int, decision: RouteDecision, step: str) -> DriverState:
        turn_id = self._mint_turn_id()
        unit_id, axis = decision.unit_id, decision.axis
        if decision.resume_question is not None:
            # A resuming probe replays the parent's exact paused question verbatim; the engine
            # guarantees that text, so it must not be regenerated by the agent.
            question = decision.resume_question
            self.session.orchestrator.present_question(
                journey_id=journey_id, unit_id=unit_id, axis=axis, turn_id=turn_id,
                question=question, step=step, save_resume_question=True,
            )
        else:
            question = self.session.run_question(
                journey_id=journey_id, unit_id=unit_id, axis=axis, turn_id=turn_id,
                step=step, save_resume_question=True,
            )
        return DriverState(
            status="awaiting_learner", journey_id=journey_id,
            projection_revision=self._revision(journey_id), turn_id=turn_id,
            unit_id=unit_id, axis=axis, question=question, step=step,
            highlight=decision.highlight, resume_question=decision.resume_question,
            reason=decision.reason,
        )

    def _teach_then_probe(self, journey_id: int, decision: RouteDecision) -> RouteDecision:
        turn_id = self._mint_turn_id()
        self.session.run_teaching(
            journey_id=journey_id, unit_id=decision.unit_id, axis=decision.axis, turn_id=turn_id)
        # After teaching an axis the engine expects the learner re-probed on that same axis.
        return RouteDecision(
            "wakeup.probe", decision.unit_id, decision.axis, "probe after teaching")

    def _distill_then_finish(self, journey_id: int, decision: RouteDecision) -> RouteDecision | None:
        unit_id = decision.unit_id
        self.session.run_distill(unit_id=unit_id, axis=decision.axis)
        unit = self._unit_row(unit_id)
        if unit["state"] == "PARKED":
            # A fatigue-switch distilled a still-live stack; parking is the finish move here.
            self.session.park(unit_id=unit_id)
            return None
        if unit["parent_id"] is not None:
            return self.session.finish_child(child_unit_id=unit_id).decision
        return self.session.finish_root(root_unit_id=unit_id).decision

    # -- terminal states ----------------------------------------------------------

    def _done(self, journey_id: int, decision: RouteDecision | None) -> DriverState:
        reason = decision.reason if decision is not None else "ladder complete"
        return DriverState(status="done", journey_id=journey_id,
                           projection_revision=self._revision(journey_id), reason=reason)

    def _parked(self, journey_id: int, decision: RouteDecision | None) -> DriverState:
        return DriverState(status="parked", journey_id=journey_id,
                           projection_revision=self._revision(journey_id),
                           reason="journey parked; resume to continue")

    # -- helpers ------------------------------------------------------------------

    def _mint_turn_id(self) -> str:
        self._turn_seq += 1
        return f"turn-{self._turn_seq}"

    def _revision(self, journey_id: int) -> int:
        return int(self.session.orchestrator.journeys.get(journey_id)["projection_revision"])

    def _unit_row(self, unit_id: int):
        row = self.session.orchestrator.db.one(
            "SELECT state, parent_id FROM units WHERE id=?", (unit_id,))
        if not row:
            raise InvariantError("driver cannot finish an unknown unit")
        return row
